
[package]
name = "hello"
version = "0.0.1"
authors = ["some author"]

[profile.dev]
opt-level=3
debug = false

[[bin]]
name = "hello"
path = "hello.rs"

[dependencies]
byteorder = "*"
rand = "*"
time = "*"
